### ISSUE TITLE
Too many redirects !

### ISSUE THREAD

**Issue by mohampooya** [Gordarg/SnowFramework#5]
well when i tried to use the link below : sariab.pressz.ir/log/in 
for the first time , my IP was from Netherlands and the site gave me a long text link:
http://sariab.pressz.ir/log/language/language/language/language/language/language/language/language/language/language/language/language/language/ ... ...

 and you have to configure the language with the different IP around the world .

**Comment by tayyebi** [comment]
https://github.com/Gordarg/SnowFramework/commit/e30006b3947ee17b8e00890b119b7b1a0984fc69
